### ISSUE TITLE
imports are deprecated

### ISSUE THREAD

**Issue by Toilal** [demonsters/prisma-mock#28]
I don't know if it can be solved easily, but I have deprecation warning when using prisma-mock.

Anyway thanks for this library, it's a life changer as it avoid to spawn a docker container with a real database to run my tests :)

```
    console.warn
      imports from "@prisma/client/runtime" are deprecated.

      at Object.<anonymous> (../../../node_modules/@prisma/client/runtime/index.js:266:2697)
      at Object.<anonymous> (../../../node_modules/prisma-mock/lib/index.js:27:19)

    console.warn
      Use "@prisma/client/runtime/library",  "@prisma/client/runtime/data-proxy" or  "@prisma/client/runtime/binary"

      at Object.<anonymous> (../../../node_modules/@prisma/client/runtime/index.js:266:2767)
      at Object.<anonymous> (../../../node_modules/prisma-mock/lib/index.js:27:19)
```

**Comment by Toilal** [comment]
I just saw there's a pull request #16 already.
